### ISSUE TITLE
'-fstack-protector-strong' not supported by compiler

### ISSUE THREAD

**Issue by Ronald826** [Neutron-Toolchains/clang-build-catalogue#1]
So I have migrated to this toolchain recently from proton-clang however, I have came across this issue:
`-fstack-protector-strong not supported by compiler.`

I have implemented this workaround into my makefile:

```
ifeq ($(cc-name),gcc)
KBUILD_CFLAGS	+= -mcpu=cortex-a76.cortex-a55 -mtune=cortex-a76.cortex-a55
endif
ifeq ($(cc-name),clang)
KBUILD_CFLAGS	+= -mcpu=cortex-a55 -mtune=cortex-a55
endif
```
in which it optimizes selected cores.

I have disabled '-fstack-protector-strong' but I would like to enable it. I haven't came across this problem with proton-clang.

Additional Information:
Windows 11 Home Single Language - WSL 2 (Ubuntu)
I have used your script to use binutils from Arch Linux.

**Comment by beakthoven** [comment]
> So I have migrated to this toolchain recently from proton-clang however, I have came across this issue: `-fstack-protector-strong not supported by compiler.`
> 
> I have implemented this workaround into my makefile:
> 
> ```
> ifeq ($(cc-name),gcc)
> KBUILD_CFLAGS	+= -mcpu=cortex-a76.cortex-a55 -mtune=cortex-a76.cortex-a55
> endif
> ifeq ($(cc-name),clang)
> KBUILD_CFLAGS	+= -mcpu=cortex-a55 -mtune=cortex-a55
> endif
> ```
> 
> in which it optimizes selected cores.
> 
> I have disabled '-fstack-protector-strong' but I would like to enable it. I haven't came across this problem with proton-clang.
> 
> Additional Information: Windows 11 Home Single Language - WSL 2 (Ubuntu) I have used your script to use binutils from Arch Linux.

Hey, If you disable `CONFIG_CC_STACKPROTECTOR_STRONG` and enable `CONFIG_CC_STACKPROTECTOR_NONE`', you should see it complaining about the actual flag(s) that are causing this issue. Please check for them and remove them.

**Comment by Ronald826** [comment]
Should I disable it in `make menuconfig` or directly in the config file? I disabled it with 'make menuconfig' and it proceeded compiling without outputing the flags (in the terminal) that are causing the issue.

**Comment by beakthoven** [comment]
> Should I disable it in `make menuconfig` or directly in the config file?

Anything would do.

> I disabled it with 'make menuconfig' and it proceeded compiling without outputing the flags (in the terminal) that are causing the issue.

Thats weird, Could you link me your kernel source including your build script/commands.

**Comment by Ronald826** [comment]
> > Should I disable it in `make menuconfig` or directly in the config file?
> 
> Anything would do.
> 
> > I disabled it with 'make menuconfig' and it proceeded compiling without outputing the flags (in the terminal) that are causing the issue.
> 
> Thats weird, Could you link me your kernel source including your build script/commands.

Here is the link to the kernel source:
https://github.com/Yukina-Supremacy/android_kernel_xiaomi_selene/blob/yukina-STOCK/Makefile

**Comment by Ronald826** [comment]
Oh I forgot, here's the build command I used:


`export HOME=$PWD` - By the time I open WSL, I open it in my directory.

`export PATH="$HOME/toolchains/neutron-clang/bin:$PATH` - The toolchain is located in the assigned `HOME` directory.

`export CROSS_COMPILE=aarch64-linux-gnu-` - Normal 64-bit ARM

`export CROSS_COMPILE_COMPAT=arm-linux-gnueabi-` - In linux version 4.14.286 (Branch: `yukina-STOCK`), it needed CROSS_COMPILE_ARM32. But, in 4.14.303+ (Branch: `twelve`)I have noticed that it fails to compile if CROSS_COMPILE_COMPAT is not used 

`export ARCH=arm64` - Building for ARM64(?)

`make selene_defconfig O=$HOME/output CC=clang LD=ld.lld DIS=llvm-dis -j$(($(nproc --all) + 1))` - make the Defconfig for the device "selene".

Navigated to the folder, "output" using `cd`

Then,

`make menuconfig CC=clang LD=ld.lld DIS=llvm-dis -j$(($(nproc --all) + 1))` - Customize the Defconfig.

Finally,

`make CC=clang LD=ld.lld DIS=llvm-dis -j$(($(nproc --all) + 1))` - to make the kernel.

**Comment by beakthoven** [comment]
> 

I tried building the kernel from the mentioned source, And i did not get any stack protector error with CONFIG_CC_STACKPROTECTOR_STRONG enabled, Though the compilation errored out after a while due to some werror complaints which is irrelevant to this issue. I would suggest double checking your toolchain paths and passing `CROSS_COMPILE` `CROSS_COMPILE_COMPAT` and `ARCH` directly to make. I would also suggest you to add `LLVM=1` to your make as your kernel supports it. Your final make command should look like this:

`make selene_defconfig O=$HOME/output ARCH=arm64 LLVM=1 CC=clang LD=ld.lld DIS=llvm-dis CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_COMPAT=arm-linux-gnueabi- -j$(($(nproc --all) + 1)`

then finally to compile it:
`make O=$HOME/output ARCH=arm64 LLVM=1 CC=clang LD=ld.lld DIS=llvm-dis CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_COMPAT=arm-linux-gnueabi- -j$(($(nproc --all) + 1)`

**Comment by Ronald826** [comment]
> > 
> 
> I tried building the kernel from the mentioned source, And i did not get any stack protector error with CONFIG_CC_STACKPROTECTOR_STRONG enabled, Though the compilation errored out after a while due to some werror complaints which is irrelevant to this issue. I would suggest double checking your toolchain paths and passing `CROSS_COMPILE` `CROSS_COMPILE_COMPAT` and `ARCH` directly to make. I would also suggest you to add `LLVM=1` to your make as your kernel supports it. Your final make command should look like this:
> 
> `make selene_defconfig O=$HOME/output ARCH=arm64 LLVM=1 CC=clang LD=ld.lld DIS=llvm-dis CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_COMPAT=arm-linux-gnueabi- -j$(($(nproc --all) + 1)`
> 
> then finally to compile it: `make O=$HOME/output ARCH=arm64 LLVM=1 CC=clang LD=ld.lld DIS=llvm-dis CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_COMPAT=arm-linux-gnueabi- -j$(($(nproc --all) + 1)`

thanks for the reply. maybe i'll redownload neutron-clang and the kernel source.
