### ISSUE TITLE
build it for linux arm too

### ISSUE THREAD

**Issue by AlirezaParsi** [Neutron-Toolchains/clang-build-catalogue#2]
I have Ubuntu arm64 but when i try build a special kernel clang it doesn't work because  it doesn't support -mcpu cortex-a77.cortex-a55 can you build this toolchain for arm64 too? i really need it because i cant compile that kernel i want i can compile other kernels but this special one no ):  

btw my kernel dev use this toolchain

**Comment by beakthoven** [comment]
> I have Ubuntu arm64 but when i try build a special kernel clang it doesn't work because it doesn't support -mcpu cortex-a77.cortex-a55 can you build this toolchain for arm64 too? i really need it because i cant compile that kernel i want i can compile other kernels but this special one no ):
> 
> btw my kernel dev use this toolchain

I didn't quite get your request, You work on a arm64 machine and want the toolchain to work on it? Btw clang doesn't support big.LITTLE optimization like gcc thats why cortex-a77.cortex-a55 is not a valid target for clang. With clang you can either compile it for cortex-a77 or cortex-a55 but not both.

**Comment by AlirezaParsi** [comment]
> > I have Ubuntu arm64 but when i try build a special kernel clang it doesn't work because it doesn't support -mcpu cortex-a77.cortex-a55 can you build this toolchain for arm64 too? i really need it because i cant compile that kernel i want i can compile other kernels but this special one no ):
> > btw my kernel dev use this toolchain
> 
> I didn't quite get your request, You work on a arm64 machine and want the toolchain to work on it? Btw clang doesn't support big.LITTLE optimization like gcc thats why cortex-a77.cortex-a55 is not a valid target for clang. With clang you can either compile it for cortex-a77 or cortex-a55 but not both.

![Screenshot_20231230-213108_Termux](https://github.com/Neutron-Toolchains/clang-build-catalogue/assets/29276037/ad6656e5-da2b-4485-886d-e5c678675d06)
my dev using your clang for compile this he said my clang have problem

**Comment by beakthoven** [comment]
> > > I have Ubuntu arm64 but when i try build a special kernel clang it doesn't work because it doesn't support -mcpu cortex-a77.cortex-a55 can you build this toolchain for arm64 too? i really need it because i cant compile that kernel i want i can compile other kernels but this special one no ):
> > > btw my kernel dev use this toolchain
> > 
> > 
> > I didn't quite get your request, You work on a arm64 machine and want the toolchain to work on it? Btw clang doesn't support big.LITTLE optimization like gcc thats why cortex-a77.cortex-a55 is not a valid target for clang. With clang you can either compile it for cortex-a77 or cortex-a55 but not both.
> 
> ![Screenshot_20231230-213108_Termux](https://private-user-images.githubusercontent.com/29276037/294400481-ad6656e5-da2b-4485-886d-e5c678675d06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzU0NTksIm5iZiI6MTcwNDQzNTE1OSwicGF0aCI6Ii8yOTI3NjAzNy8yOTQ0MDA0ODEtYWQ2NjU2ZTUtZGEyYi00NDg1LTg4NmQtZTVjNjc4Njc1ZDA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA2MTIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2NGFiZTkyYTJkOGZhYzlhYTlhNzBlZDYyOWRkNDFhNjMxODlmMzkzNTNiM2Q4NzRhNjljMmI2OTFiNjI5NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4beeCoL_lKNKNGSqaHQHeWt4AjsQOCnnniIg9ea2qjI) my dev using your clang for compile this he said my clang have problem

There is no problem with the toolchain, Your kernel must be adapted to use proper mcpu flags for clang. Clang doesn't support bi-cluster optimization like gcc so you cant optimize for cortex-a77.cortex-a55, you can either optimize it for cortex-a77 or cortex-a55 by passing it to -mcpu flag.

**Comment by AlirezaParsi** [comment]
i did this with 
CFLAGS="-mcpu=cortex.a77" but it didn't worked.
also if you wanna see, this is kernel source:
http://github.com/EmanuelCN/kernel_xiaomi_sm8250
ps : vendor/alioth_defconfig
thank you for helping me.

**Comment by beakthoven** [comment]
> -mcpu=cortex.a77

it must be -mcpu=cortex-a77

**Comment by AlirezaParsi** [comment]
it didn't worked 
i used export -mcpu=cortex-a77
and also used make ./out -j4 -mcpu=cortex-a77 

i faced errors :
![Screenshot_20240105-101019_Termux](https://github.com/Neutron-Toolchains/clang-build-catalogue/assets/29276037/ef98660e-1de5-47f2-b36f-69b4f2261ffa)

**Comment by AlirezaParsi** [comment]
![Screenshot_20240105-101139_Termux](https://github.com/Neutron-Toolchains/clang-build-catalogue/assets/29276037/61a23422-2a79-4909-bcc6-8787e1ef4f89)
also if you wanna see my build script

**Comment by beakthoven** [comment]
> it didn't worked i used export -mcpu=cortex-a77 and also used make ./out -j4 -mcpu=cortex-a77
> 
> i faced errors : ![Screenshot_20240105-101019_Termux](https://private-user-images.githubusercontent.com/29276037/294414342-ef98660e-1de5-47f2-b36f-69b4f2261ffa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0Mzk3NzAsIm5iZiI6MTcwNDQzOTQ3MCwicGF0aCI6Ii8yOTI3NjAzNy8yOTQ0MTQzNDItZWY5ODY2MGUtMWRlNS00N2YyLWIzNmYtNjliNGYyMjYxZmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA3MjQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjOWI4NDM4NGQ5OTRkMGVlMDNhMmEyNDA1MjQ0YzI4ZjE4M2UzYmE4NmU4ODYyMTFkYjhhNmVkMDUxODUwNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.73gLEf-XDZ_IwtYNwppyE8iQTTtK7kKyDEzZQ9ftPQQ)

mcpu is a clang flag and must be passed in cflags section in Makefile. And you need to compile with proper make flags to initialize the appropriate defconfig. I would advise you to read proper documentation for building linux kernel and passing custom clang flags in makefile. Till then i am closing this issue as its unrelated to the actual toolchain.
